<?php

namespace Database\Seeders;

use App\Models\Mobil;
use Illuminate\Database\Seeder;

class MobilSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mobils = [
            [
                'merk' => 'Toyota',
                'model' => 'Avanza',
                'tahun' => '2024',
                'tipe' => 'MPV',
                'harga_baru' => 180000000,
                'harga_jual_kembali' => 144000000,
                'fitur_keamanan' => 6,
                'fitur_kenyamanan' => 8,
                'efisiensi_bahan_bakar' => 14.5,
                'performa' => 1500,
                'pajak' => 1800000,
                'gambar' => '/storage/mobils/1765025651_vzDbum6Xs4Ib8gmmVus7nahli4V3QSjkMdPxWfUY.jpg',
            ],
            [
                'merk' => 'Honda',
                'model' => 'City',
                'tahun' => '2024',
                'tipe' => 'City Car',
                'harga_baru' => 165000000,
                'harga_jual_kembali' => 132000000,
                'fitur_keamanan' => 5,
                'fitur_kenyamanan' => 7,
                'efisiensi_bahan_bakar' => 16.2,
                'performa' => 1200,
                'pajak' => 1650000,
                'gambar' => '/storage/mobils/1765025993_Group-43.png',
            ],
            [
                'merk' => 'Suzuki',
                'model' => 'Ertiga',
                'tahun' => '2024',
                'tipe' => 'MPV',
                'harga_baru' => 170000000,
                'harga_jual_kembali' => 136000000,
                'fitur_keamanan' => 5,
                'fitur_kenyamanan' => 7,
                'efisiensi_bahan_bakar' => 15.1,
                'performa' => 1500,
                'pajak' => 1700000,
                'gambar' => '/storage/mobils/1765026118_pearl-snow.png',
            ],
            [
                'merk' => 'Honda',
                'model' => 'Accord',
                'tahun' => '2024',
                'tipe' => 'Sedan',
                'harga_baru' => 520000000,
                'harga_jual_kembali' => 390000000,
                'fitur_keamanan' => 8,
                'fitur_kenyamanan' => 9,
                'efisiensi_bahan_bakar' => 12.5,
                'performa' => 1500,
                'pajak' => 4000000,
                'gambar' => '/storage/mobils/1765026536_2024-Honda-Accord-Hybrid-Black.png',
            ],
            [
                'merk' => 'Toyota',
                'model' => 'Corolla',
                'tahun' => '2024',
                'tipe' => 'Sedan',
                'harga_baru' => 385000000,
                'harga_jual_kembali' => 280000000,
                'fitur_keamanan' => 7,
                'fitur_kenyamanan' => 8,
                'efisiensi_bahan_bakar' => 13.2,
                'performa' => 1600,
                'pajak' => 3000000,
                'gambar' => '/storage/mobils/1765028703_LE_Corolla.png',
            ],
            [
                'merk' => 'Wuling',
                'model' => 'Air EV',
                'tahun' => '2024',
                'tipe' => 'Electric Car',
                'harga_baru' => 340000000,
                'harga_jual_kembali' => 255000000,
                'fitur_keamanan' => 6,
                'fitur_kenyamanan' => 8,
                'efisiensi_bahan_bakar' => 0.0,
                'performa' => 0,
                'pajak' => 0,
                'gambar' => '/storage/mobils/1765028761_screen-shot-2024-10-02-at-92845-pm-2b2823870c37bec67c6c20af813c7f3c-63eacdadef7645aa47c3ab10b0f9abcd.png',
            ],
            [
                'merk' => 'Daihatsu',
                'model' => 'Rocky',
                'tahun' => '2024',
                'tipe' => 'Compact SUV',
                'harga_baru' => 225000000,
                'harga_jual_kembali' => 168750000,
                'fitur_keamanan' => 6,
                'fitur_kenyamanan' => 7,
                'efisiensi_bahan_bakar' => 13.8,
                'performa' => 1200,
                'pajak' => 2250000,
                'gambar' => '/storage/mobils/1767874061_10182-daihatsu-rocky.jpg',
            ],
            [
                'merk' => 'Hyundai',
                'model' => 'Creta',
                'tahun' => '2024',
                'tipe' => 'Compact SUV',
                'harga_baru' => 245000000,
                'harga_jual_kembali' => 183750000,
                'fitur_keamanan' => 6,
                'fitur_kenyamanan' => 8,
                'efisiensi_bahan_bakar' => 14.2,
                'performa' => 1500,
                'pajak' => 2450000,
                'gambar' => '/storage/mobils/1765029125_cr2id-optic_33-1.png',
            ],
            [
                'merk' => 'BMW',
                'model' => 'X5',
                'tahun' => '2024',
                'tipe' => 'Premium SUV',
                'harga_baru' => 1200000000,
                'harga_jual_kembali' => 840000000,
                'fitur_keamanan' => 9,
                'fitur_kenyamanan' => 10,
                'efisiensi_bahan_bakar' => 11.0,
                'performa' => 3000,
                'pajak' => 12000000,
                'gambar' => '/storage/mobils/1765029156_202308291544-main.cropped_1693298707.jpg',
            ],
            [
                'merk' => 'Mercedes-Benz',
                'model' => 'C-Class',
                'tahun' => '2024',
                'tipe' => 'Premium SUV',
                'harga_baru' => 850000000,
                'harga_jual_kembali' => 595000000,
                'fitur_keamanan' => 9,
                'fitur_kenyamanan' => 10,
                'efisiensi_bahan_bakar' => 10.5,
                'performa' => 2000,
                'pajak' => 8500000,
                'gambar' => '/storage/mobils/1765029217_model2.png',
            ],
            [
                'merk' => 'Toyota',
                'model' => 'Raize',
                'tahun' => '2021',
                'tipe' => 'Compact SUV',
                'harga_baru' => 278000000,
                'harga_jual_kembali' => 225000000,
                'fitur_keamanan' => 10,
                'fitur_kenyamanan' => 11,
                'efisiensi_bahan_bakar' => 16,
                'performa' => 1000,
                'pajak' => 4591000,
                'gambar' => '/storage/mobils/1765190026_60cb591d83d73.png',
            ],
            [
                'merk' => 'Hyundai',
                'model' => 'Creta',
                'tahun' => '2021',
                'tipe' => 'Compact SUV',
                'harga_baru' => 370500000,
                'harga_jual_kembali' => 255000000,
                'fitur_keamanan' => 11,
                'fitur_kenyamanan' => 14,
                'efisiensi_bahan_bakar' => 16,
                'performa' => 1500,
                'pajak' => 6071000,
                'gambar' => '/storage/mobils/1765191360_hyundai-creta_169.jpeg',
            ],
            [
                'merk' => 'Honda',
                'model' => 'HR-V',
                'tahun' => '2022',
                'tipe' => 'Compact SUV',
                'harga_baru' => 452000000,
                'harga_jual_kembali' => 355000000,
                'fitur_keamanan' => 13,
                'fitur_kenyamanan' => 13,
                'efisiensi_bahan_bakar' => 15,
                'performa' => 1500,
                'pajak' => 7375000,
                'gambar' => '/storage/mobils/1765191692_1650793649_honda-all-new-hr-v-2022-indonesia-suv-impresif-luar-biasa.png',
            ],
            [
                'merk' => 'Daihatsu',
                'model' => 'Rocky',
                'tahun' => '2021',
                'tipe' => 'Compact SUV',
                'harga_baru' => 252000000,
                'harga_jual_kembali' => 195000000,
                'fitur_keamanan' => 9,
                'fitur_kenyamanan' => 10,
                'efisiensi_bahan_bakar' => 17,
                'performa' => 1000,
                'pajak' => 4175000,
                'gambar' => '/storage/mobils/1765191916_Daihatsu-Rocky-varian-1.0-R-TC-ADS.png.png',
            ],
            [
                'merk' => 'Toyota',
                'model' => 'Yaris',
                'tahun' => '2023',
                'tipe' => 'Compact SUV',
                'harga_baru' => 403000000,
                'harga_jual_kembali' => 325000000,
                'fitur_keamanan' => 12,
                'fitur_kenyamanan' => 12,
                'efisiensi_bahan_bakar' => 27,
                'performa' => 1500,
                'pajak' => 6591000,
                'gambar' => '/storage/mobils/1765192100_1692091394_toyota-all-new-yaris-cross-hev-suv-hybrid-lokal-yang-andal.jpg',
            ],
        ];

        foreach ($mobils as $mobil) {
            Mobil::create($mobil);
        }
    }
}
